Vagrant.configure("2") do |config|
    config.vm.box = "debian/bullseye64"
    config.vm.provider "virtualbox" do |v|
        v.gui = false
        v.cpus = 1
        v.memory = 1024
    end
    config.vm.define "ntp_lab" do |m|
        m.vm.network "public_network", type: "dhcp"
    end
    config.vm.define "client" do |m|
        m.vm.network "public_network", type: "dhcp"
    end
end
